name: Build, Test and Run App in Simulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Run App in Simulator
    runs-on: macos-13  # Use the latest macOS runner with available Xcode

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install dependencies (if needed)
        run: |
          # e.g., install CocoaPods or dependencies
          # pod install
          # npm install, etc.

      - name: Build the project
        run: |
          xcodebuild -scheme "SoundSphere" -project "SoundSphere.xcodeproj" -destination 'platform=iOS Simulator,name=iPhone 14' build

      - name: Run Tests
        run: |
          xcodebuild test -scheme "SoundSphere" -project "SoundSphere.xcodeproj" -destination 'platform=iOS Simulator,name=iPhone 14'

      - name: Run App in Simulator
        run: |
          # Run the app on the simulator
          xcrun simctl boot "iPhone 14"
          xcrun simctl install booted ./build/Build/Products/Debug-iphonesimulator/SoundSphere.app
          xcrun simctl launch booted com.yourcompany.SoundSphere
